name: FortUTF Windows GFortran 11

on: [push]

jobs:
  build:
    name: 'Windows Latest'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.24.x'
      - name: Build Tests
        run: |
            choco upgrade mingw --version="'11.2.0'" -y
            choco install -y make
            cmake -G "Unix Makefiles" -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: |
             ls -la build
             chmod +x FortUTF_Tests.exe
             .\FortUTF_Tests.exe